@baseUrl = http://localhost:3000

########

# @name GetAllComponents
GET {{baseUrl}}/component HTTP/1.1

########

# @name GetAllComponentsAsAny
GET {{baseUrl}}/component HTTP/1.1
Accept: */*

########

# @name GetAllComponentsAsTurtle
GET {{baseUrl}}/component HTTP/1.1
Accept: text/turtle

########

# @name GetAllComponentsAsJSONLD
GET {{baseUrl}}/component HTTP/1.1
Accept: application/ld+json

########

# @name GetAllComponentsAsUnacceptable
GET {{baseUrl}}/component HTTP/1.1
Accept: bla

########

# @name GetAllComponentsAsJSON
GET {{baseUrl}}/component HTTP/1.1
Accept: application/json

########

# @name FilterComponents
POST {{baseUrl}}/component/query HTTP/1.1
Accept: application/json
Content-Type: application/json

{  
    "uri": "https://node.semcom.digita.ai/c/001"
}

########

# @name SaveComponent
POST {{baseUrl}}/component/save HTTP/1.1
Accept: application/json
Content-Type: application/json

{  
     "uri": "foo5/bar",
     "label": "test5",
     "description": "test5",
     "author": "test5",
     "version": "test5",
     "latest": "true"
}