:toc:
:toclevels: 3


= Refactor components and add logic using custom fetch functions


== Author(s)

* Wouter Termont


== References

* Project: https://github.com/digita-ai/dgt-semcom[@digita-ai/semcom-components]
//* Branch: `feature/658432185-initial-setup-docs`


== Overview of the proposed solution

This analysis describes a refactor of the initial components implementing the SemCom Component interface, so that they make use of the new mechanism with custom fetch functions. The same steps should be taken for all existing components (currently one for profiles and one for payslips)


== Detailed analysis of the suggested implementation

The current initial implementations use a `rdfData` function setting a single `@internalProperty` called `name`. Remove them, and add a new static function returning a properties object. For example:

[source,typescript]
----
static get properties() {
  return {
    name: String
  }
}
----

Both components already contain private properties and public setters for the new `fetch` function and `entry` field. Implement the logic so that on any update of the field, the component

- logs an error if the function is not set, or
- uses the function to get the data from the entry uri.

The component should then read and parse the data (e.g. using N3.js), and store any information it needs in the properties object. This can be done directly, e.g. not via `this.properties().name` but via `this.name`. Make sure each component has the right properties for its functionality.

When the data logic is completed, update the HTML template returned by the `render` function, and add the necessary CSS to the static `styles` function, to present the data in the component.

Mockups of the profile and payslips components can be found on link:https://www.figma.com/file/pPdyUg0GbiH36wyxcnLsW6/Demo---SemCom?node-id=0%3A1[Figma].

Note that you can use the `serve` script to mock a client app, whose logic resides entirely in the root's `index.ts`. When updating the components, this logic will also need to be updated.
