== Technical Specification: Create models and services

=== Author(s)

* Stijn Taelemans

=== References

* Functional analysis: see semcom-core docs
* https://www.wrike.com/open.htm?id=637357186[Wrike task]

* Branch: `feature/637357186-create-models-services`
* Projects:
** https://github.com/digita-ai/semcom[semcom]

=== Introduction

==== Overview

This specification is about the creation of the SemCom models and services

==== Terminology

SemCom: Semantic Component.

Node/repository: a place where SemCom metadata is stored.

App developer: A developer who uses the SDK for their application.

==== Out of scope

`SemComInput` and its implementations are described in the class diagram, but should not be created yet. The same goes for `SemComClientService`.

=== Solution

_This is a proposed solution and is open to change. If you feel some things can be done better, please discuss with this document's link:###authors[author(s)]._

Add documentation and unit tests for every model and service described below. You can use the descriptions from this document as documentation.

==== semcom-core

===== Models

====== ComponentMetadata

Create 'component-metadata.model.ts' under lib/component/models.

Contains extra information about a `Component`.

The attributes of this model can be found in the class diagram.

Some example `ComponentMetadata` objects: 

[source, json]
----
{
    "uri": "https://components.digita.ai/album",
    "label": "Image Album Component",
    "description":  "Component that renders images",
    "author":  "digita.ai",
    "version":  "1.0.0",
    "latest":  true,
}
----

[source, json]
----
{
    "uri": "https://components.digita.ai/payslip",
    "label": "Payslip Component",
    "description":  "Component that renders a payslip",
    "author":  "digita.ai",
    "version":  "1.0.0",
    "latest":  true,
}
----

====== Component

Create 'component.model.ts' under lib/component/models.

The class used to create 
In it's current state, this model only has one attribute: `metadata`. The idea is that when a developer wants to create a `Component`, he or she extends both `Component` and `HTMLElement`, the result being a Web Component with an extra attribute `metadata`.

The attributes of this model can be found in the class diagram. The `render` method is included in the diagram, but should not be implemented for now.

===== Services

====== QueryService<T>

Create 'component.model.ts' under lib/component/services/query.

An interface that defines 

The attributes and functions of this model can be found in the class diagram. 

====== ManageService<T>

Create 'component.model.ts' under lib/component/services/manage.

The attributes and functions of this model can be found in the class diagram. 



====== AbstractQueryComponentService

Create 'query-component-abstract.service.ts' under lib/component/services/query.

Implements `QueryService<ComponentMetadata>`.

The attributes and functions of this model can be found in the class diagram. 


====== QueryComponentInMemoryService

Create 'query-component-in-memory.service.ts' under lib/component/services/query.

Extends `AbstractQueryComponentService`.

The attributes and functions of this model can be found in the class diagram. 


====== AbstractManageComponentService

Create 'manage-component-abstract.service.ts' under lib/component/services/manage.

Implements `ManageService<ComponentMetadata>`.

The attributes and functions of this model can be found in the class diagram. 


====== ManageComponentInMemoryService

Create 'manage-component-in-memory.service.ts' under lib/component/services/manage.

Extends `AbstractManageComponentService`.

The attributes and functions of this model can be found in the class diagram. 


==== semcom-node

===== Services

====== BaseComponentService

Create 'component.service.ts' under lib/component/services.

This is the interface for the `Component` service to be used in the back-end.

The attributes and functions of this model can be found in the class diagram. 


====== ComponentService

Create 'component.service.ts' under lib/component/services.

Implements `ComponentService`.

The attributes and functions of this model can be found in the class diagram. 


==== semcom-sdk

===== Services

====== QueryComponentRemoteService

Create 'query-component-remote.service.ts' under lib/services. Remove current SemComService.

Extends `AbstractQueryComponentService`.

The attributes and functions of this model can be found in the class diagram. 

This service is the one used by a developer to retrieve `Component` s. `this.repository` is the URI of the repository. `this.query` send an HTTP GET request to the correct `semcom-node` endpoint with the `filter` in its body. (I believe it is `/all` at the moment)  

The backend should handle the filtering logic and returns a list of `ComponentMetadata`.
