== Technical Specification: Create models and services

=== Author(s)

* Stijn Taelemans

=== References

* Functional analysis: see semcom-core docs
* https://www.wrike.com/open.htm?id=637357186[Wrike task]

* Branch: `feature/637357186-create-models-services`
* Projects:
** https://github.com/digita-ai/semcom[semcom]

=== Introduction

==== Overview

This specification is about the creation of the SemCom models and services

==== Terminology

SemCom: Semantic Component.

Node/repository: a place where SemCom metadata is stored.

App developer: A developer who uses the SDK for their application.

==== Out of scope

`SemComInput` and its implementations are described in the class diagram, but should not be created yet. The same goes for `SemComClientService`.

=== Solution

_This is a proposed solution and is open to change. If you feel some things can be done better, please discuss with this document's link:###authors[author(s)]._

==== semcom-core

===== Models

====== SemComMetadata

Create 'semcom-metadata.model.ts' under lib/semcom/models.

This model describes the metadata of a `SemCom`.

The attributes of this model can be found in the class diagram.

Some example `SemComMetadata` objects: 

[source, json]
----
{
    "uri": "https://components.digita.ai/album",
    "name": "Image Album Component",
    "label":  "Component that renders images",
    "author":  "digita.ai",
    "version":  "1.0.0",
    "latest":  "true",
}
----

[source, json]
----
{
    "uri": "https://components.digita.ai/payslip",
    "name": "Payslip Component",
    "label":  "Component that renders a payslip",
    "author":  "digita.ai",
    "version":  "1.0.0",
    "latest":  "true",
}
----

====== SemCom

Create 'semcom.model.ts' under lib/semcom/models.

In it's current state, this model only has one attribute: `metadata`. The idea is that when a developer wants to create a `SemCom`, he or she extends both `SemCom` and `HTMLElement`, the result being a Web Component with an extra attribute `metadata`.

The attributes of this model can be found in the class diagram. The `render` method is included in the diagram, but should not be implemented for now.

===== Services

====== SemComService

Create 'semcom-abstract.service.ts' under lib/semcom/services.

A user can enter a partial `SemComMetadata` to the `query` which will be used to filter. For example, if a user wants a `SemCom` from `author` 'digita', they pass `{ author: 'digita' }` to the `query` method.

====== SemComNodeInMemoryService

Extends `SemComService`.

Create 'semcom-node.service.ts' under lib/semcom/services. Replaces `ComponentService`.

This service extends `SemComService`. The service already exists under `ComponentService`, simply rename it and change `all()` to comply with the class diagram. You also need to change the signature of `semcom-node`'s controller to return `SemComMetadata`.

====== SemComNodeClientService

Extends `SemComService`.

Create 'semcom-node.service.ts' under lib/semcom/services. Replaces `ComponentService`.

This service is the one used by an app developer to retrieve one (or more) SemCom(s). Its `query` method retrieves components from `this.repository` that match a `filter`. The `get` method retrieves a single component based on the component's `uri`. (Call the `query` method with a simple uri filter)

==== semcom-node

===== Models & Services

By removing/renaming the `Component` model, some imports will break in this project. Replace with the new `SemCom` model. Rename `Component` references to `SemCom` where necessary. (controller, transformer, ...)
