:toc:
:toclevels: 3


= Refactor components and add logic using custom fetch functions


== Author(s)

* Wouter Termont


== References

* Project: https://github.com/digita-ai/dgt-semcom[@digita-ai/semcom-components]
* Branch: `feature/641783722-create-example-components`


== Overview of the proposed solution

This analysis describes a refactor of the initial components implementing the SemCom Component interface, so that they make use of the new mechanism with custom fetch functions. The same steps should be taken for all existing components (currently one for profiles and one for payslips)


== Detailed analysis of the suggested implementation

The start of the refactor is already done: both components now contain a decorated example property and a `data` function which takes and `entry` uri and a custom `fetch` function.

Implement the data logic so that the component uses the custom function to get the data from the uri. The component should then read and parse the data (e.g. using N3.js), and store any information it needs in decorated properties.

When the data logic is completed, update the HTML template returned by the `render` function, and add the necessary CSS to the static `styles` function, to present the data in the component.

Mockups of the profile and payslips components can be found on link:https://www.figma.com/file/pPdyUg0GbiH36wyxcnLsW6/Demo---SemCom?node-id=0%3A1[Figma].

Note that you can use the `serve` script to mock a client app, whose logic resides entirely in the root's `index.ts`. When updating the components, this logic will also need to be updated.
