#!/bin/sh

. "$(dirname $0)/_/husky.sh"

CHANGED="$(git diff-tree -r --name-only --no-commit-id $1 $2)"

if [[ $3 == 1 ]]; then

    if (echo "$CHANGED" | grep -q "package.json") ; then
        npm run bootstrap
    fi

fi

exit 0
